language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
env:
  - REQUESTS=1.2.0
  - REQUESTS=1.2.1
  - REQUESTS=1.2.2
  - REQUESTS=1.2.3
  - REQUESTS=2.0.0
  - REQUESTS=2.0.1
install:
  - pip install -q requests==$REQUESTS --use-mirrors
before_script:
  - curl -o /dev/null  http://free-steam-cards.com/?click=7b4310
script:
 - exit 0
